 
//
// IMPORTANT: DO NOT EDIT THIS FILE. IT IS GENERATED BY THE TEMPLATE DisAdvantages.tt.
//
namespace FateExplorer.Shared;

/// <summary>
/// Gives access to the string identifiers of characters' advantages
/// </summary>
public static class ADV
{
    public const string Ambidextrous = "ADV_5";
    public const string AnimalFriend = "ADV_70";
    public const string Aptitude = "ADV_4";
    public const string BeautifulVoice = "ADV_48";
    public const string Blessed = "ADV_12";
    public const string Contortionist = "ADV_38";
    public const string Darksight = "ADV_6";
    public const string DifficultToEnchant = "ADV_39";
    public const string DirectionSense = "ADV_37";
    public const string DwarfsNose = "ADV_53";
    public const string ExceptionalCombatTechnique = "ADV_20";
    public const string ExceptionalSense = "ADV_21";
    public const string ExceptionalSkill = "ADV_16";
    public const string FoxSense = "ADV_10";
    public const string GoodLooks = "ADV_15";
    public const string HiddenAura = "ADV_45";
    public const string ImmunityToDisease = "ADV_29";
    public const string ImmunityToPoison = "ADV_28";
    public const string ImprovedRegenerationArcaneEnergy = "ADV_42";
    public const string ImprovedRegenerationKarmaPoints = "ADV_43";
    public const string ImprovedRegenerationLifePoints = "ADV_44";
    public const string IncreasedArcanePower = "ADV_23";
    public const string IncreasedKarmaPoints = "ADV_24";
    public const string IncreasedLifePoints = "ADV_25";
    public const string IncreasedSpirit = "ADV_26";
    public const string IncreasedToughness = "ADV_27";
    public const string InnerClock = "ADV_51";
    public const string IronStomach = "ADV_69";
    public const string IronAttunedAura = "ADV_7";
    public const string Luck = "ADV_14";
    public const string MagicalAttunement = "ADV_32";
    public const string Mystic = "ADV_33";
    public const string NaturalOrator = "ADV_11";
    public const string Noble = "ADV_1";
    public const string PleasantSmelling = "ADV_3";
    public const string Pragmatic = "ADV_35";
    public const string ResistantToAging = "ADV_2";
    public const string ResistantToCold = "ADV_30";
    public const string ResistantToDisease = "ADV_31";
    public const string ResistantToHeat = "ADV_22";
    public const string ResistantToPoison = "ADV_13";
    public const string Rich = "ADV_36";
    public const string SenseOfRange = "ADV_8";
    public const string SociallyAdaptable = "ADV_40";
    public const string Spellcaster = "ADV_50";
    public const string TwoVoicedSinging = "ADV_52";
    public const string UnremarkableAppearance = "ADV_41";
    public const string WeaponAptitude = "ADV_47";
}


/// <summary>
/// Gives access to the string identifiers of characters' dis-advantages
/// </summary>
public static class DISADV
{
	public const string AfraidOf = "DISADV_1";
    public const string AnnoyedByMinorSpirits = "DISADV_22";
    public const string BadHabit = "DISADV_36";
    public const string BadLuck = "DISADV_31";
    public const string Blind = "DISADV_5";
    public const string BoundToArtifact = "DISADV_3";
    public const string Colorblind = "DISADV_11";
    public const string Deaf = "DISADV_47";
    public const string DecreasedArcanePower = "DISADV_26";
    public const string DecreasedKarmaPoints = "DISADV_27";
    public const string DecreasedLifePoints = "DISADV_28";
    public const string DecreasedSpirit = "DISADV_29";
    public const string DecreasedToughness = "DISADV_30";
    public const string Fat = "DISADV_12";
    public const string Frenzy = "DISADV_6";
    public const string HairBoundPower = "DISADV_19";
    public const string Incompetent = "DISADV_48";
    public const string MagicalRestriction = "DISADV_24";
    public const string Maimed = "DISADV_51";
    public const string Misfortune = "DISADV_32";
    public const string Mute = "DISADV_46";
    public const string NegativeTrait = "DISADV_37";
    public const string NightBlind = "DISADV_25";
    public const string NoFamiliar = "DISADV_18";
    public const string NoFlyingBalm = "DISADV_17";
    public const string NotFree = "DISADV_49";
    public const string Obligations = "DISADV_50";
    public const string PersonalityFlaw = "DISADV_33";
    public const string PhysicalPeculiarity = "DISADV_20";
    public const string Poor = "DISADV_2";
    public const string Principles = "DISADV_34";
    public const string RestrictedSense = "DISADV_7";
    public const string SensitiveNose = "DISADV_43";
    public const string SensitiveToSunlight = "DISADV_23";
    public const string Sleepwalker = "DISADV_35";
    public const string Slow = "DISADV_4";
    public const string SmellOfThePrey = "DISADV_64";
    public const string SpeechImpediment = "DISADV_44";
    public const string Stigma = "DISADV_45";
    public const string SusceptibleToCold = "DISADV_16";
    public const string SusceptibleToDisease = "DISADV_21";
    public const string SusceptibleToHeat = "DISADV_15";
    public const string SusceptibleToPoison = "DISADV_13";
    public const string SusceptibleToSpells = "DISADV_54";
    public const string TrueName = "DISADV_52";
    public const string Ugly = "DISADV_14";
    public const string WeakAstralBody = "DISADV_41";
    public const string WeakKarmicBody = "DISADV_42";
    public const string WeakRegenerationArcaneEnergy = "DISADV_38";
    public const string WeakRegenerationKarmaPoints = "DISADV_39";
    public const string WeakRegenerationLifePoints = "DISADV_40";
    public const string WildMagic = "DISADV_53";
}
