// IMPORTANT: DO NOT EDIT THIS FILE. IT IS GENERATED BY THE TEMPLATE "IconsFE.tt".
namespace MudBlazor;

public static class IconsFE {
    const string Ligaturisation = "fe "; // CSS selector for ligaturisation
    const string ClassPrefix = "fe-";    // Prefix to access the CSS class that returns the icon
    const string Prefix = Ligaturisation + ClassPrefix;

    public static string Concat(string IconName) => Prefix + IconName;

    public static string Success => Prefix + nameof(Success);
    public static string Botch => Prefix + nameof(Botch);
    public static string PotionArcane => Prefix + nameof(PotionArcane);
    public static string PotionLife => Prefix + nameof(PotionLife);
    public static string LocalMallClear => Prefix + nameof(LocalMallClear);
    public static string Ulisses => Prefix + nameof(Ulisses);
    public static string BackHandLeft => Prefix + nameof(BackHandLeft);
    public static string Sword => Prefix + nameof(Sword);
    public static string Blindfold => Prefix + nameof(Blindfold);
    
    // DEITIES
    public static string Boron => Prefix + nameof(Boron);
    public static string Efferd => Prefix + nameof(Efferd);
    public static string Firun => Prefix + nameof(Firun);
    public static string Hesinde => Prefix + nameof(Hesinde);
    public static string Ingerimm => Prefix + nameof(Ingerimm);
    public static string Peraine => Prefix + nameof(Peraine);
    public static string Phex => Prefix + nameof(Phex);
    public static string Praios => Prefix + nameof(Praios);
    public static string Rahja => Prefix + nameof(Rahja);
    public static string Rondra => Prefix + nameof(Rondra);
    public static string Travia => Prefix + nameof(Travia);
    public static string Tsa => Prefix + nameof(Tsa);
    public static string NamelessOne => Prefix + nameof(NamelessOne);
    
    // DICE d6
    public static string D6(int d) => Concat($"{nameof(D6)}_{d}");
    public static string D6_1 => Prefix + nameof(D6_1);
    public static string D6_2 => Prefix + nameof(D6_2);
    public static string D6_3 => Prefix + nameof(D6_3);
    public static string D6_4 => Prefix + nameof(D6_4);
    public static string D6_5 => Prefix + nameof(D6_5);
    public static string D6_6 => Prefix + nameof(D6_6);
    
    // MADAS MARK - MOON PHASES
    
    /// <summary>
    /// Get icons by moon phase
    /// </summary>
    /// <param name="phase">1-12, 1 is new moon (dead mada), 4 is half, 7 is full moon (wheel),, 
    /// 10 is half, 12 the phase before new moon</param>
    /// <returns></returns>
    public static string Moon(MoonPhase phase) => Concat($"{nameof(Moon)}Phase{((int)phase)}");
}