// IMPORTANT: DO NOT EDIT THIS FILE. IT IS GENERATED BY THE TEMPLATE "IconsFE.tt".
namespace MudBlazor;

using FateExplorer.Shared;

public static class IconsFE {
    const string Ligaturisation = "fe "; // CSS selector for ligaturisation
    const string ClassPrefix = "fe-";    // Prefix to access the CSS class that returns the icon
    const string Prefix = Ligaturisation + ClassPrefix;

    public static string Concat(string IconName) => Prefix + IconName;

    public static string Success => Prefix + nameof(Success);
    public static string Falldown => Prefix + nameof(Falldown);
    public static string PotionArcane => Prefix + nameof(PotionArcane);
    public static string PotionLife => Prefix + nameof(PotionLife);
    public static string LocalMallClear => Prefix + nameof(LocalMallClear);
    public static string Ulisses => Prefix + nameof(Ulisses);
    public static string BackHandLeft => Prefix + nameof(BackHandLeft);
    public static string Blindfold => Prefix + nameof(Blindfold);
    public static string BrassKnuckles => Prefix + nameof(BrassKnuckles);
    public static string Sword => Prefix + nameof(Sword);
    public static string Flail => Prefix + nameof(Flail);
    public static string Spear => Prefix + nameof(Spear);
    public static string Cramped => Prefix + nameof(Cramped);
    public static string Mounted0_Stand => Prefix + nameof(Mounted0_Stand);
    public static string Mounted1_Walk => Prefix + nameof(Mounted1_Walk);
    public static string Mounted2_Trot => Prefix + nameof(Mounted2_Trot);
    public static string Mounted3_Gallop => Prefix + nameof(Mounted3_Gallop);
    public static string Onfoot0_Stand => Prefix + nameof(Onfoot0_Stand);
    public static string Onfoot1_Walk => Prefix + nameof(Onfoot1_Walk);
    public static string Water0_Dry => Prefix + nameof(Water0_Dry);
    public static string Water1_Knee => Prefix + nameof(Water1_Knee);
    public static string Water2_Waist => Prefix + nameof(Water2_Waist);
    public static string Water3_Chest => Prefix + nameof(Water3_Chest);
    public static string Water4_Neck => Prefix + nameof(Water4_Neck);
    public static string Water5_Submerged => Prefix + nameof(Water5_Submerged);
    public static string Vision0_Clear => Prefix + nameof(Vision0_Clear);
    public static string Vision1_Impaired => Prefix + nameof(Vision1_Impaired);
    public static string Vision2_ShapesOnly => Prefix + nameof(Vision2_ShapesOnly);
    public static string Vision3_Barely => Prefix + nameof(Vision3_Barely);
    public static string Vision4_None => Prefix + nameof(Vision4_None);
    public static string DemonCrown => Prefix + nameof(DemonCrown);
    
    // DEITIES
    public static string Boron => Prefix + nameof(Boron);
    public static string Efferd => Prefix + nameof(Efferd);
    public static string Firun => Prefix + nameof(Firun);
    public static string Hesinde => Prefix + nameof(Hesinde);
    public static string Ingerimm => Prefix + nameof(Ingerimm);
    public static string Peraine => Prefix + nameof(Peraine);
    public static string Phex => Prefix + nameof(Phex);
    public static string Praios => Prefix + nameof(Praios);
    public static string Rahja => Prefix + nameof(Rahja);
    public static string Rondra => Prefix + nameof(Rondra);
    public static string Travia => Prefix + nameof(Travia);
    public static string Tsa => Prefix + nameof(Tsa);
    public static string NamelessOne => Prefix + nameof(NamelessOne);
        // OBJECT GROUPS
    public static string Ammunition => Prefix + nameof(Ammunition);
    public static string ArmourLamellar => Prefix + nameof(ArmourLamellar);
    public static string WeaponAccessoires => Prefix + nameof(WeaponAccessoires);
    public static string Shirt => Prefix + nameof(Shirt);
    public static string TreasureMap => Prefix + nameof(TreasureMap);
    public static string Torch => Prefix + nameof(Torch);
    public static string Bandages => Prefix + nameof(Bandages);
    public static string Chest => Prefix + nameof(Chest);
    public static string Chain => Prefix + nameof(Chain);
    public static string BurglarTools => Prefix + nameof(BurglarTools);
    public static string Tools => Prefix + nameof(Tools);
    public static string Telescope => Prefix + nameof(Telescope);
    public static string Jewellery => Prefix + nameof(Jewellery);
    public static string Gem => Prefix + nameof(Gem);
    public static string Stationary => Prefix + nameof(Stationary);
    public static string Book => Prefix + nameof(Book);
    public static string MagicArtefact => Prefix + nameof(MagicArtefact);
    public static string PestleMortar => Prefix + nameof(PestleMortar);
    public static string PotionMadness => Prefix + nameof(PotionMadness);
    public static string HerbsReed => Prefix + nameof(HerbsReed);
    public static string Flute => Prefix + nameof(Flute);
    public static string Shisha => Prefix + nameof(Shisha);
    public static string HorseShoe => Prefix + nameof(HorseShoe);
    public static string Transport => Prefix + nameof(Transport);
    public static string SnakeSkin => Prefix + nameof(SnakeSkin);
    public static string SunSceptre => Prefix + nameof(SunSceptre);
        // ANIMAL
    public static string AnimalToad => Prefix + nameof(AnimalToad);
    public static string AnimalGoat => Prefix + nameof(AnimalGoat);
    public static string AnimalSheep => Prefix + nameof(AnimalSheep);
    public static string AnimalCow => Prefix + nameof(AnimalCow);
    public static string AnimalElefant => Prefix + nameof(AnimalElefant);
    public static string AnimalDragon => Prefix + nameof(AnimalDragon);
        // DICE d6
    public static string D6(int d) => Concat($"{nameof(D6)}_{d}");
    public static string D6_1 => Prefix + nameof(D6_1);
    public static string D6_2 => Prefix + nameof(D6_2);
    public static string D6_3 => Prefix + nameof(D6_3);
    public static string D6_4 => Prefix + nameof(D6_4);
    public static string D6_5 => Prefix + nameof(D6_5);
    public static string D6_6 => Prefix + nameof(D6_6);
    

    // ACTIONS/COMBAT SUCCESS/FAIL/...
        public static string UnarmedBotch => Prefix + nameof(UnarmedBotch);
        public static string UnarmedFail => Prefix + nameof(UnarmedFail);
        public static string UnarmedSuccess => Prefix + nameof(UnarmedSuccess);
        public static string UnarmedCritical => Prefix + nameof(UnarmedCritical);
        public static string MeleeBotch => Prefix + nameof(MeleeBotch);
        public static string MeleeFail => Prefix + nameof(MeleeFail);
        public static string MeleeSuccess => Prefix + nameof(MeleeSuccess);
        public static string MeleeCritical => Prefix + nameof(MeleeCritical);
        public static string RangedBotch => Prefix + nameof(RangedBotch);
        public static string RangedFail => Prefix + nameof(RangedFail);
        public static string RangedSuccess => Prefix + nameof(RangedSuccess);
        public static string RangedCritical => Prefix + nameof(RangedCritical);
        public static string ParryBotch => Prefix + nameof(ParryBotch);
        public static string ParryFail => Prefix + nameof(ParryFail);
        public static string ParrySuccess => Prefix + nameof(ParrySuccess);
        public static string ParryCritical => Prefix + nameof(ParryCritical);
        public static string DodgeBotch => Prefix + nameof(DodgeBotch);
        public static string DodgeFail => Prefix + nameof(DodgeFail);
        public static string DodgeSuccess => Prefix + nameof(DodgeSuccess);
        public static string DodgeCritical => Prefix + nameof(DodgeCritical);
    


    // MADAS MARK - MOON PHASES
    
    /// <summary>
    /// Get icons by moon phase
    /// </summary>
    /// <param name="phase">Current moon phase</param>
    /// <returns></returns>
    /// <remarks>1-12, 1 is new moon (dead mada), 4 is half, 7 is full moon (wheel),
    /// 10 is half, 12 the phase before new moon. Adapt MoonPhase accordingly.</remarks>
    public static string Moon(MoonPhase phase) => Concat($"{nameof(Moon)}Phase{(int)phase + 1}");
}