@startuml Combat

title Character Combat Relationships

namespace CharacterModel {
    class CharacterM {
      + List<WeaponM>
    }


    class WeaponM {
      + int AtSkill
      + int PaSkill
    }
}

namespace ViewModel {
    class WeaponViMo {
      # WeaponM WeaponM
      + int AtSkill
      + int PaSkill
    }

    class HandsViMo {
      + WeaponViMo MainWeapon
      + WeaponViMo OffWeapon
    }

    class TheHeroViMo {
      + HandsViMo Hands
    }
}


ViewModel.WeaponViMo *-right- CharacterModel.WeaponM
ViewModel.TheHeroViMo *-right- CharacterModel.CharacterM

ViewModel.TheHeroViMo "1" *-up- "1" ViewModel.HandsViMo: has a pair of
ViewModel.HandsViMo "1" *-up- "2" ViewModel.WeaponViMo: carry each a

CharacterModel.CharacterM "1" o-up-- "n" CharacterModel.WeaponM: owns


@enduml