//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aventuria.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aventuria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die D ähnelt.
        /// </summary>
        internal static string MiddenrealmDucatAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmDucatAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ducat ähnelt.
        /// </summary>
        internal static string MiddenrealmDucatName {
            get {
                return ResourceManager.GetString("MiddenrealmDucatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔇 ähnelt.
        /// </summary>
        internal static string MiddenrealmDucatSymbol {
            get {
                return ResourceManager.GetString("MiddenrealmDucatSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die H ähnelt.
        /// </summary>
        internal static string MiddenrealmHalerAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmHalerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haler ähnelt.
        /// </summary>
        internal static string MiddenrealmHalerName {
            get {
                return ResourceManager.GetString("MiddenrealmHalerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔥 ähnelt.
        /// </summary>
        internal static string MiddenrealmHalerSymbol {
            get {
                return ResourceManager.GetString("MiddenrealmHalerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die K ähnelt.
        /// </summary>
        internal static string MiddenrealmKreutzerAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmKreutzerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreutzer ähnelt.
        /// </summary>
        internal static string MiddenrealmKreutzerName {
            get {
                return ResourceManager.GetString("MiddenrealmKreutzerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔨 ähnelt.
        /// </summary>
        internal static string MiddenrealmKreutzerSymbol {
            get {
                return ResourceManager.GetString("MiddenrealmKreutzerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die S ähnelt.
        /// </summary>
        internal static string MiddenrealmSilverthalerAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmSilverthalerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silverthaler ähnelt.
        /// </summary>
        internal static string MiddenrealmSilverthalerName {
            get {
                return ResourceManager.GetString("MiddenrealmSilverthalerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔖 ähnelt.
        /// </summary>
        internal static string MiddenrealmSilverthalerSymbol {
            get {
                return ResourceManager.GetString("MiddenrealmSilverthalerSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carat ähnelt.
        /// </summary>
        internal static string WeightCarat {
            get {
                return ResourceManager.GetString("WeightCarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ct ähnelt.
        /// </summary>
        internal static string WeightCaratAbbr {
            get {
                return ResourceManager.GetString("WeightCaratAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuboid ähnelt.
        /// </summary>
        internal static string WeightCuboid {
            get {
                return ResourceManager.GetString("WeightCuboid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C ähnelt.
        /// </summary>
        internal static string WeightCuboidAbbr {
            get {
                return ResourceManager.GetString("WeightCuboidAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gran ähnelt.
        /// </summary>
        internal static string WeightGran {
            get {
                return ResourceManager.GetString("WeightGran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gr ähnelt.
        /// </summary>
        internal static string WeightGranAbbr {
            get {
                return ResourceManager.GetString("WeightGranAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ounce ähnelt.
        /// </summary>
        internal static string WeightOunce {
            get {
                return ResourceManager.GetString("WeightOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oz ähnelt.
        /// </summary>
        internal static string WeightOunceAbbr {
            get {
                return ResourceManager.GetString("WeightOunceAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℥ ähnelt.
        /// </summary>
        internal static string WeightOunceSymbol {
            get {
                return ResourceManager.GetString("WeightOunceSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scruple ähnelt.
        /// </summary>
        internal static string WeightScruple {
            get {
                return ResourceManager.GetString("WeightScruple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die s ähnelt.
        /// </summary>
        internal static string WeightScrupleAbbr {
            get {
                return ResourceManager.GetString("WeightScrupleAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℈ ähnelt.
        /// </summary>
        internal static string WeightScrupleSymbol {
            get {
                return ResourceManager.GetString("WeightScrupleSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stone ähnelt.
        /// </summary>
        internal static string WeightStone {
            get {
                return ResourceManager.GetString("WeightStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die st ähnelt.
        /// </summary>
        internal static string WeightStoneAbbr {
            get {
                return ResourceManager.GetString("WeightStoneAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ﬆ ähnelt.
        /// </summary>
        internal static string WeightStoneSymbol {
            get {
                return ResourceManager.GetString("WeightStoneSymbol", resourceCulture);
            }
        }
    }
}
