//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aventuria.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aventuria.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dᵈ ähnelt.
        /// </summary>
        internal static string AlanfaDirhamAbbr {
            get {
                return ResourceManager.GetString("AlanfaDirhamAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dirham ähnelt.
        /// </summary>
        internal static string AlanfaDirhamName {
            get {
                return ResourceManager.GetString("AlanfaDirhamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ↀ ähnelt.
        /// </summary>
        internal static string AlanfaDoubloonAbbr {
            get {
                return ResourceManager.GetString("AlanfaDoubloonAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doubloon ähnelt.
        /// </summary>
        internal static string AlanfaDoubloonName {
            get {
                return ResourceManager.GetString("AlanfaDoubloonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die O ähnelt.
        /// </summary>
        internal static string AlanfaOrealAbbr {
            get {
                return ResourceManager.GetString("AlanfaOrealAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Oreal ähnelt.
        /// </summary>
        internal static string AlanfaOrealName {
            get {
                return ResourceManager.GetString("AlanfaOrealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ō ähnelt.
        /// </summary>
        internal static string AlanfaSmallOrealAbbr {
            get {
                return ResourceManager.GetString("AlanfaSmallOrealAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Small Oreal ähnelt.
        /// </summary>
        internal static string AlanfaSmallOrealName {
            get {
                return ResourceManager.GetString("AlanfaSmallOrealName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AT ähnelt.
        /// </summary>
        internal static string AndrathalerAbbr {
            get {
                return ResourceManager.GetString("AndrathalerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Andrathaler ähnelt.
        /// </summary>
        internal static string AndrathalerName {
            get {
                return ResourceManager.GetString("AndrathalerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bL ähnelt.
        /// </summary>
        internal static string BornlandLumpAbbr {
            get {
                return ResourceManager.GetString("BornlandLumpAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lump ähnelt.
        /// </summary>
        internal static string BornlandLumpName {
            get {
                return ResourceManager.GetString("BornlandLumpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bP ähnelt.
        /// </summary>
        internal static string BornlandPennyAbbr {
            get {
                return ResourceManager.GetString("BornlandPennyAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Penny ähnelt.
        /// </summary>
        internal static string BornlandPennyName {
            get {
                return ResourceManager.GetString("BornlandPennyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die bS ähnelt.
        /// </summary>
        internal static string BornlandSlightlingAbbr {
            get {
                return ResourceManager.GetString("BornlandSlightlingAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slightling ähnelt.
        /// </summary>
        internal static string BornlandSlightlingName {
            get {
                return ResourceManager.GetString("BornlandSlightlingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horasian Empire ähnelt.
        /// </summary>
        internal static string CountryHO {
            get {
                return ResourceManager.GetString("CountryHO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Middenrealm ähnelt.
        /// </summary>
        internal static string CountryMI {
            get {
                return ResourceManager.GetString("CountryMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ᚷ ähnelt.
        /// </summary>
        internal static string DwarvenArganbroxAbbr {
            get {
                return ResourceManager.GetString("DwarvenArganbroxAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arganbrox ähnelt.
        /// </summary>
        internal static string DwarvenArganbroxName {
            get {
                return ResourceManager.GetString("DwarvenArganbroxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ᛏ ähnelt.
        /// </summary>
        internal static string DwarvenAtebroxAbbr {
            get {
                return ResourceManager.GetString("DwarvenAtebroxAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Atebrox ähnelt.
        /// </summary>
        internal static string DwarvenAtebroxName {
            get {
                return ResourceManager.GetString("DwarvenAtebroxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ᚢ ähnelt.
        /// </summary>
        internal static string DwarvenAuromoxAbbr {
            get {
                return ResourceManager.GetString("DwarvenAuromoxAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auromox ähnelt.
        /// </summary>
        internal static string DwarvenAuromoxName {
            get {
                return ResourceManager.GetString("DwarvenAuromoxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DP ähnelt.
        /// </summary>
        internal static string DwarvenPennyAbbr {
            get {
                return ResourceManager.GetString("DwarvenPennyAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Penny ähnelt.
        /// </summary>
        internal static string DwarvenPennyName {
            get {
                return ResourceManager.GetString("DwarvenPennyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DS ähnelt.
        /// </summary>
        internal static string DwarvenShillingAbbr {
            get {
                return ResourceManager.GetString("DwarvenShillingAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shilling ähnelt.
        /// </summary>
        internal static string DwarvenShillingName {
            get {
                return ResourceManager.GetString("DwarvenShillingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DT ähnelt.
        /// </summary>
        internal static string DwarvenThalerAbbr {
            get {
                return ResourceManager.GetString("DwarvenThalerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thaler ähnelt.
        /// </summary>
        internal static string DwarvenThalerName {
            get {
                return ResourceManager.GetString("DwarvenThalerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔻 ähnelt.
        /// </summary>
        internal static string HorasdorAbbr {
            get {
                return ResourceManager.GetString("HorasdorAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Horasdor ähnelt.
        /// </summary>
        internal static string HorasdorName {
            get {
                return ResourceManager.GetString("HorasdorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔇 ähnelt.
        /// </summary>
        internal static string MiddenrealmDucatAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmDucatAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ducat ähnelt.
        /// </summary>
        internal static string MiddenrealmDucatName {
            get {
                return ResourceManager.GetString("MiddenrealmDucatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔥 ähnelt.
        /// </summary>
        internal static string MiddenrealmHalerAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmHalerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Haler ähnelt.
        /// </summary>
        internal static string MiddenrealmHalerName {
            get {
                return ResourceManager.GetString("MiddenrealmHalerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔨 ähnelt.
        /// </summary>
        internal static string MiddenrealmKreutzerAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmKreutzerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kreutzer ähnelt.
        /// </summary>
        internal static string MiddenrealmKreutzerName {
            get {
                return ResourceManager.GetString("MiddenrealmKreutzerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 𝔖 ähnelt.
        /// </summary>
        internal static string MiddenrealmSilverthalerAbbr {
            get {
                return ResourceManager.GetString("MiddenrealmSilverthalerAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Silverthaler ähnelt.
        /// </summary>
        internal static string MiddenrealmSilverthalerName {
            get {
                return ResourceManager.GetString("MiddenrealmSilverthalerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cr ähnelt.
        /// </summary>
        internal static string NostrianCrownAbbr {
            get {
                return ResourceManager.GetString("NostrianCrownAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crown ähnelt.
        /// </summary>
        internal static string NostrianCrownName {
            get {
                return ResourceManager.GetString("NostrianCrownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die G ähnelt.
        /// </summary>
        internal static string PaaviGuilderAbbr {
            get {
                return ResourceManager.GetString("PaaviGuilderAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guilder ähnelt.
        /// </summary>
        internal static string PaaviGuilderName {
            get {
                return ResourceManager.GetString("PaaviGuilderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Carat ähnelt.
        /// </summary>
        internal static string WeightCarat {
            get {
                return ResourceManager.GetString("WeightCarat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ct ähnelt.
        /// </summary>
        internal static string WeightCaratAbbr {
            get {
                return ResourceManager.GetString("WeightCaratAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cuboid ähnelt.
        /// </summary>
        internal static string WeightCuboid {
            get {
                return ResourceManager.GetString("WeightCuboid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C ähnelt.
        /// </summary>
        internal static string WeightCuboidAbbr {
            get {
                return ResourceManager.GetString("WeightCuboidAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gran ähnelt.
        /// </summary>
        internal static string WeightGran {
            get {
                return ResourceManager.GetString("WeightGran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die gr ähnelt.
        /// </summary>
        internal static string WeightGranAbbr {
            get {
                return ResourceManager.GetString("WeightGranAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ounce ähnelt.
        /// </summary>
        internal static string WeightOunce {
            get {
                return ResourceManager.GetString("WeightOunce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die oz ähnelt.
        /// </summary>
        internal static string WeightOunceAbbr {
            get {
                return ResourceManager.GetString("WeightOunceAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℥ ähnelt.
        /// </summary>
        internal static string WeightOunceSymbol {
            get {
                return ResourceManager.GetString("WeightOunceSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Scruple ähnelt.
        /// </summary>
        internal static string WeightScruple {
            get {
                return ResourceManager.GetString("WeightScruple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die s ähnelt.
        /// </summary>
        internal static string WeightScrupleAbbr {
            get {
                return ResourceManager.GetString("WeightScrupleAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ℈ ähnelt.
        /// </summary>
        internal static string WeightScrupleSymbol {
            get {
                return ResourceManager.GetString("WeightScrupleSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die stone ähnelt.
        /// </summary>
        internal static string WeightStone {
            get {
                return ResourceManager.GetString("WeightStone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die st ähnelt.
        /// </summary>
        internal static string WeightStoneAbbr {
            get {
                return ResourceManager.GetString("WeightStoneAbbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ﬆ ähnelt.
        /// </summary>
        internal static string WeightStoneSymbol {
            get {
                return ResourceManager.GetString("WeightStoneSymbol", resourceCulture);
            }
        }
    }
}
